baseURL = 'https://k-m-crawford.onrender.com/'
languageCode = 'en-us'
title = 'KM Crawford'
disableKinds = ['taxonomy', 'term']
[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 10
[[menu.main]]
  name = 'CV'
  url = '/cv'
  weight = 20
[[menu.main]]
  name = 'Projects'
  url = '/projects'
  weight = 30
[[menu.main]]
  name = 'About'
  url = '/about'
  weight = 40
[[menu.main]]
  name = 'Contact'
  url = '/contact'
  weight = 40
